[project]
name = "uma"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bs4>=0.0.2",
    "requests>=2.32.3",
]

[tool.pytest.ini_options]
testpaths = ["."]
python_files = ["*.py"]
pythonpath = "."
addopts = "--import-mode=importlib"
